regen-network/regen-server

- server/Server.ts
ref: https://github.com/regen-network/regen-registry/issues/838
Needed so that the new testnet branch deploys (https://hambach--regen-registry.netlify.app/ and https://redwood--regen-registry.netlify.app/) can interact with the registry server.
---
I have...
I have...
> Allow CORS origin for hambach/redwood branch deploys

- .github/dependabot.yml
Part of: https://github.com/regen-network/regen-registry/issues/849
---
This adds a dependabot config file which tells it to target the `dev` branch when submitting dependency updates.
I have...
I have...
> Configure dependabot target-branch to dev

- server/package.json
Closes: https://github.com/regen-network/regen-registry/issues/882
This adds ts-node and typescript back as dependencies in the `server/package.json`. Without these listed we get the failures documented in the issue above, when we do a build where `NODE_ENV=production`. 
---
I have...
I have...
> Fix "tsc not found" error in the heroku build process

- server/routes/metadata-graph.ts
Closes: https://github.com/regen-network/regen-registry/issues/890
- This adjusts the /metadata-graph endpoint
to send just the metadata for a given IRI.
- Previously we had an extra key in the response.
---
I have...
I have...
> Flatten the metadata graph response

- server/middleware/imageOptimizer.ts
- server/package.json
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/867
- Depending on the redis connection string, we will connect
to redis using either TLS or non-TLS.
- A redis connection string that starts with redis:// is
a non-TLS TCP connection.
- Whereas a connection string that starts with rediss:// is
a TLS TCP connection.
- ioredis is added as a dependency to make this work with
the express-sharp library.
---
I have...
I have...
> Use either TLS/non-TLS TCP to connect to Redis

- package.json
The manual deployment to production failed with these messages:
```
➜  registry-server git:(master) ✗ git push regen-registry-server master:main                                                                                                                                   [30/53]
Enumerating objects: 3414, done.
Counting objects: 100% (3414/3414), done.
Delta compression using up to 8 threads
Compressing objects: 100% (1975/1975), done.
Writing objects: 100% (3414/3414), 15.32 MiB | 3.46 MiB/s, done.
Total 3414 (delta 2204), reused 2120 (delta 1336), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-18 stack
remote: -----> Using buildpack: heroku/nodejs
remote: -----> Node.js app detected
remote:
remote: -----> …
```
> Fix heroku nodejs engine version

- server/Server.ts
- server/package.json
- yarn.lock
Ref: https://github.com/regen-network/regen-registry/issues/928
This adds the following postgraphile plugin: https://github.com/graphile-contrib/postgraphile-plugin-connection-filter so we can filter by certain jsonb fields value, eg filter projects by `regen:vcsProjectId` which is a field that is in the metadata of VCS projects. This can be used to map an on-chain credit batch (which also references some `regen:vcsProjectId` in its metadata) to an off-chain project (until we have on-chain projects).
Also see https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/issues/31
Front-end PR upcoming
---
I have...
*All items are …
> Add postgraphile ConnectionFilterPlugin

- package.json
- server/Server.ts
- server/package.json
- yarn.lock
To be merged along with https://github.com/regen-network/regen-web/pull/1223
Closes: 
- an issue raised in this PR: https://github.com/regen-network/regen-web/pull/1223#issuecomment-1246320074
When updating `@cosmjs` dependencies the `content-type` used in ledger requests changed from `text/plain;charset=UTF-8` to `application/json` which cause an error while parsing the request body.
To fix this issue, the dependency [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) has been bumped and a provided interceptor `fixRequestBody` is applied before the request body is parsed to stringify it if the content is `application/json`.
See https://github.com/chimurai/http-proxy-middleware/blob/v2.0.6/src/handlers/fix-request-body.ts for more details.
- …
> fix: ledger proxy json

- server/Server.ts
fix: only handle uncaught exceptions with sentry
This results in less noise in sentry. It's a significant problem for us since it's causing us to use nearly all of our monthly capacity in sentry. This is mostly an oversight on my part during set up.
A further improvement we can do later is to prevent the local development environment from sending sentry errors. BUT right now, I don't think it's necessary, because the amount of garbage events we were sending prior to this change was much much greater. 
TL;DR 74k transactions were used for metadata not found errors (our limit per month is 80k 😬 )
---
I have...
*All items are required. Please add a note …
> fix: only handle uncaught exceptions with sentry

- server/.env.example
- server/Server.ts
Closes: https://github.com/regen-network/regen-registry/issues/1340
This PR sets an environment variable to control which environments sentry will be used in. We will set this variable only in the production heroku environment. So this means Sentry will only be used in production.
---
I have...
I have...
> feat: add flag to toggle sentry init and use

- README.md
- package.json
- server/middleware/imageOptimizer.ts
- sql/V2_16__add_utility_schema.sql
- sql/V2_17__drop_keyv_table_from_public_schema.sql
- yarn.lock
Closes: regen-network/regen-registry#1311
Recently we added support for postgres as a backend to the image caching layer (primarily used for storing `express-sharp` image resizing results). Previously we were using redis as the caching backend for this.
Mysteriously, using postgres as a backend worked in staging but it did not work in production. It turned out to be an SSL connection issue and the `@keyv/postgres` package recently added SSL support.
This PR upgrades that package to the new version, and it adjusts our code to make use of the SSL certificate when connecting to both the staging and production database. It's quite similar to what we do in `pool.ts`.
Note:
- Post-merge to production, set `IMAGE_CACHING_BACKEND=postgres`.
- Check logs to make sure there are no errors
- Test …
> fix: use ssl for postgres image caching in production

- server/Server.ts
This is a fix for a bug I introduced while setting up [this lint rule](https://github.com/regen-network/registry-server/pull/269#discussion_r1091108336).
Some of our modules depend on having environment variables set prior to importing.
Therefore, in local development, `dotenv.config` must be called before we import these modules.
This is the easiest fix, I don't think it's worth a further refactor right now to avoid this problem.
It's a problem that can be better solved at a later time, but certainly not a critical one.
---
I have...
your handle next to the …
> fix: some imports need to be after dotenv for local dev

- server/__tests__/db/project.delete.policy.test.ts
- server/__tests__/db/project.insert.policy.test.ts
- server/__tests__/db/project.update.policy.test.ts
- sql/V2_22__update_project_policies.sql
- sql/authn/R__get_current_addrs.sql
Closes: https://github.com/regen-network/regen-registry/issues/1552
Currently, this PR adds policies to the project table which introduces the rules below.
An authenticated user (the `auth_user` role):
1. can only create new project if they specify the admin as one of the addresses which belongs to their account.
2. is not allowed to delete any project, even there own.
(i wasn't sure what the rule should be for delete so i went with a safe rule)
3. can only update any projects that they are an admin for.
can only update the admin of a project to an address which belongs to their account.
Additionally, any user (the `app_user` role) can select all projects.
---
please add links to any relevant follow …
> feat: add new policies for projects

- server/Server.ts
Fixes: issue where cookie was not being set for deploy previews and the dev environment due to the fact that heroku uses a reverse proxy.
Issue was uncovered in this related PR:
https://github.com/regen-network/regen-web/pull/1819
the [docs for "cookieSession"][1] in the server say this:
> be sure to read how to [setup Express behind proxies][2] or the cookie may not ever set correctly.
this amounts to use adding this in our code:
```javascript
app.set('trust proxy', true);
```
I tested that even with this our local environment is still working.
Note:
- It may be possible to choose a more restrictive value here, but I think this is OK.
I don't see a huge security concern, since we have CSRF protection.
[1]: http://expressjs.com/en/resources/middleware/cookie-session.html
[2]: …
> fix: add trust proxy setting

- Dockerfile
Docker composes was failing because it was prompting to do an upgrade.
This adds a flag to automatically accept upgrades.
---
I have...
I have...
> fix: apt get docker

- .gitignore
- package.json
- server/Server.ts
- server/package.json
- server/routes/graphiql.ts
- server/views/graphiql.html
Deploys: #318 
Note: This also re-enables csrf protection on the graphql endpoint. 
---
I have...
I have...
> feat: add graphiql instance that uses csrf-csrf (#318)

- iri-gen/index.ts
I started to get the following error when running the iri gen script:
```sh
% yarn gen project.json
yarn run v1.22.17
$ ts-node index.ts project.json
/Users/mariegauthier/registry-server/node_modules/ts-node/src/index.ts:843
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
^
TSError: ⨯ Unable to compile TypeScript:
index.ts:18:16 - error TS2349: This expression is not callable.
Type '{ default: { (args?: string[], opts?: Opts): ParsedArgs; <T>(args?: string[], opts?: Opts): T & ParsedArgs; <T extends ParsedArgs>(args?: string[], opts?: Opts): T; }; }' has no call signatures.
18   const argv = minimist(process.argv.slice(2), { boolean: true });
~~~~~~~~
index.ts:5:1
5 import * as minimist from 'minimist';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Type originates at this …
```
> fix: minimist import

- server/Server.ts
- server/types.ts
While working with #384 I noticed two small things that could be cleaned up:
1. When I ran yarn lint the location of the call to `dotenv.config` was shifted in such a way that would break things when running locally. So I moved it into the already existing eslint ignore block so it doesn't get shifted around and break.
2. Switched `UserIncomingMessage` type with `UserRequest` in the `pgSettings` function, this provides a more accurate type for that parameter.
---
I have...
I have...
> fix: small improves in server/Server.ts

- server/package.json
Getting the following error in heroku: `server: middleware/loginHelpers.ts(7,11): error TS2339: Property 'session' does not exist on type 'UserRequest'.` because `req.session` comes from `@types/cookie-session`
---
I have...
I have...
> fix: move @types/cookie-session to dep instead of devDep

- server/package.json
Moving @types/express-fileupload away from dev dep to dep so the app doesn't crash on heroku.
---
I have...
I have...
> fix: move @types/express-fileupload to dep

- server/__tests__/e2e/wallet-auth.logout.test.ts
- server/__tests__/utils.ts
- server/routes/wallet-auth.ts
If you log out from account A, then log in with account B, account A was still part of the authenticated accounts list, which shouldn't be the case. Logging out should log you out from all authenticated accounts.
---
I have...
I have...
> fix: logout session auth accounts

- .github/workflows/registryServer.yml
ref: https://github.com/regen-network/regen-server/pull/455
---
I have...
I have...
> chore: only run ci on branches dev and master

- server/middleware/googleStrategy.ts
- server/routes/auth.ts
- server/types.ts
Part of: https://regennetwork.atlassian.net/jira/software/c/projects/ENG/boards/51?selectedIssue=APP-111
This is to allow to redirect to the project creation basic info form after logging in with google instead of the user profile page (default). On the front-end, this will be achieved by passing a query parameter `createProject` to /auth/google endpoint.
See flow on https://www.figma.com/file/OBJXPR0vdjnWb9fOYHA6Sg/Add-more-CTAs-to-list-a-project?type=design&node-id=9-11756&mode=design&t=LBznjJd7SfFhRQuZ-0
---
I have...
your handle next to the items reviewed if …
> feat: APP-111 choose redirect google oauth route based on state from query param

- iri-gen/index.ts
Closes: https://regennetwork.atlassian.net/browse/APP-96
Adds support for generating IRI's for raw datasets.  Full functionality is now as follows:
- `yarn gen [path/to/file.json]` will generate an IRI using a graph content hash by default for all JSON files (and can insert to Postgres when the `--insert` flag is added)
- `yarn gen [path/to/file.pdf]` will generate an IRI using a raw content hash for any other filetype extension besides JSON
- `yarn gen [path/to/file.json] --raw` can be used (adding the `--raw` flag) if one wants to use a raw content hash for IRI generation of a JSON file.
---
I have...
*All items are required. Please add a note if …
> feat(irigen): Add CLI functionality for generating raw IRI in yarn script

- .github/workflows/registryServer.yml
- server/.env-test
- server/__tests__/e2e/files.profiles.test.ts
- server/__tests__/e2e/files.projects.test.ts
- server/routes/files.ts
The /files DELETE endpoint was only supporting projects media deletion, now it supports profile media deletion too (profile and background images).
ref: https://regennetwork.atlassian.net/browse/APP-114?atlOrigin=eyJpIjoiOGE2YzJkZTgzMjE2NDVlNGE3NGUxZjYyMmY0YmI1ZDQiLCJwIjoiaiJ9
---
I have...
I have...
> fix: APP-114 allow profile media deletion
