regen-network/regen-server

- server/routes/buyers-info.ts
- sql/R__get_contact_email.sql
- sql/V1_43__purchase_stripe_id_index.sql
- sql/V1_44__organization_member_select_policy.sql
- sql/V1_45__new_columns.sql
- sql/V1_46__vintage_period.sql
- sql/V1_47__project_updates.sql
ref: https://github.com/regen-network/regen-registry/issues/192
> Certificate

- server/Server.ts
> [WIP] image optimization iii

- server/Server.ts
> [WIP] image optimization iv

- server/tsconfig.json
I believe this should fix the recent build error I introduced
> Remove jest types from tsconfig

- schema/project-page.ttl
- schema/project-plan.ttl
closes: https://github.com/regen-network/regen-registry/issues/484
> Create SHACL graph for Project Page on boarding forms

- flyway.conf
- schema/project-page.ttl
- schema/project-plan.ttl
- sql/V1_63__credit_class_uri.sql
- sql/V1_64__project_updates.sql
- sql/V1_65__project_creator.sql
- sql/V1_66__project_policy.sql
ref: https://github.com/regen-network/regen-registry/issues/531
Front-end PR: https://github.com/regen-network/regen-web/pull/649
> Add SHACL validation

- server/__tests__/db/functions/issue_credits.test.ts
- server/__tests__/db/functions/transfer_credits.test.ts
- server/__tests__/db/helpers.ts
- sql/R__create_project.sql
- sql/R__get_available_credits.sql
- sql/R__issue_credits.sql
- sql/R__transfer_credits.sql
- sql/V1_67__external_program_support.sql
- sql/V1_68__credit_vintage_initial_distribution.sql
ref: https://github.com/regen-network/regen-registry/issues/563
Front-end PR in progress
> Add external program support and update related functions and tests

- sql/V1_70__standards_update.sql
- sql/V1_71__fix_document_id.sql
ref: regen-network/regen-registry#660
PR on regen-registry-standards: https://github.com/regen-network/regen-registry-standards/pull/3
> Add migration to reflect updated registry standards

- sql/R__retire_credits.sql
- sql/R__transfer_credits.sql
references: regen-network/regen-registry#646
[Frontend PR](https://github.com/regen-network/regen-web/pull/747)
> Add metadata field to retire_credits function

- flyway.conf
- sql/V1_72__project_originator.sql
- sql/V1_73__project_creator_policies.sql
ref: regen-network/regen-registry#676
> Project Roles database migrations

- sql/R__get_available_credits.sql
closes: regen-network/regen-registry#682
> Fix get_available_credits sql function

- server/Server.ts
Related: regen-network/regen-registry#739
Creates a proxy endpoint for REST ledger requests.
---
I have...
I have...
> Proxy for ledger REST

- README.md
- sql/V1_82__add_on_chain_id_to_credit_class.sql
Part of: regen-network/regen-registry#805
Pairs with [#857](https://github.com/regen-network/regen-web/pull/857)
This makes it possible to look up credit-classes by class_id (such as `C01`), which makes it possible to link to a ledger credit class.
---
I have...
I have...
> onChainId for credit_class

- sql/V1_83__credit_class_uri_unique.sql
Ref: https://github.com/regen-network/regen-registry/issues/851
Added this so we can fetch a credit class by uri from GraphQL (`creditClassByUri` query).
---
I have...
I have...
> Add credit class uri unique migration

- README.md
Adds to the README details about manual Heroku deployments.
---
I have...
I have...
> Add manual deploy docs to README

- .github/dependabot.yml
Configure dependabot for monthly updates, 5 per month.
---
I have...
I have...
> Monthly updates for dependabot

- README.md
- server/Server.ts
- server/package.json
- server/routes/metadata-graph.ts
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/942
This adds API documentation for certain endpoints on the registry-server.
swagger-jsdoc allows you to write jsdoc style annotations for your API endpoints. it also is responsible for parsing these annotations and converting them into a swagger format. swagger-express-ui takes that output and generates the following page:
the set of libraries above do not auto-generate your documentation based off of express endpoints or request properties that are accessed in the endpoint, etc. however, these libraries do autogenerate your api docs based off your jsdoc comments.
i tested out [swagger-autogen](https://www.npmjs.com/package/swagger-autogen) which does generate some documentation automatically but it requires a certain …
> Add API documentation using swagger-jsdoc and swagger-express-ui

- server/.env.example
- server/Server.ts
Ref: https://github.com/regen-network/regen-registry/issues/983
---
I have...
I have...
> feat: Add proxies for temporary testnet endpoints for Regen Ledger v4.0

- server/Server.ts
Forgot to do that as part of the v4 branch setup.
---
I have...
I have...
> chore: Add v4 to allowed origins

- server/Server.ts
Ref: #208
---
I have...
I have...
> Dev into master

- yarn.lock
Related: #213 
TL;DR after merging several dependabot upgrades into `dev`, there was a merge conflict between `dev` and `master`, this PR fixes that conflict. It was a conflict in yarn.lock related to the `minimist`
---
I have...
I have...
> Fix conflict for yarn.lock

- server/middleware/jwt.ts
Related: https://github.com/regen-network/registry-server/pull/201
The recently applied express-jwt upgrade changed the way their primary import statement works, this PR adjusts our code to that change.
---
I have...
I have...
> Fix expressjwt after upgrade

- yarn.lock
Related: #217 
I think I made a mistake with the merge in the PR above, this adjusts that change. I believe this is done correctly now.
Here is how I did it this time:
```
$ git checkout dev
$ git merge origin/master  # conflict
$ yarn
$ git commit
```
The yarn package manager has the ability to fix conflicts, so that last step resolves it. `https://github.com/yarnpkg/yarn/pull/3544`
---
I have...
I have...
> Fix merge conflict yarn.lock

- sql/V2_15__add_on_chain_id_to_project.sql
Needed for: regen-network/regen-registry#994
- add on_chain_id to project table, create index
---
I have...
I have...
> feat: add on_chain_id to project table, create index

- flyway.js
Addresses failed migration command due to missing flyway-commandline tar.gz artifacts upstream by pinning the flyway version.
Upstream issue to resolve missing artifacts: https://issues.sonatype.org/browse/MVNCENTRAL-7548
i.e. failed build message:
```
remote: Verifying deploy... done.            
remote: Running release command...                                                                                                                                                                                    
remote:                                         
remote: yarn run v1.22.19                                                                                                                                                                                             
remote: $ flyway -c …
```
> chore: pin flyway version

- server/Server.ts
- server/package.json
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/1110
This adds integration to Sentry, following the official Sentry <> express guide:
https://docs.sentry.io/platforms/node/guides/express/
---
I have...
I have...
> feat: integrate sentry

- server/middleware/imageOptimizer.ts
- server/package.json
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/922
It turned out that the [`keyv-s3`](https://github.com/microlinkhq/keyv-s3) back-end I proposed using is not compatible with the setup we have. I didn't dig deeply into why, because I realized that it could be easier to just use the [`@keyv/postgres`](https://github.com/jaredwray/keyv/tree/main/packages/postgres) back-end instead. Additionally, the `@keyv/postgres` package, unlike `keyv-s3` is maintained under the `keyv` monorepo, and so I expect a bit more actively developed/maintained.
Currently the redis instance we are using is 100MB (which is consistently being maxed out). Our postgres database has 17500MB (17.5 GB) of free storage space. That's a big increase. Additionally, I learned that we can make use of brotli …
> feat: add support for and default to postgres as image caching backend

- yarn.lock
Fixes conflict in: #242 
---
I have...
I have...
> PR 242 merge conflict fix

- server/Server.ts
- server/middleware/imageOptimizer.ts
- server/package.json
- yarn.lock
Closes: https://github.com/regen-network/registry-server/pull/245
Please see the two-dot diff:
https://github.com/regen-network/registry-server/compare/master..dev
---
I have...
I have...
> fix: only handle uncaught exceptions with sentry

- server/Server.ts
Add `main` deploy preview pattern to CORS. (ie: https://639aee43101e366250794f27--regen-registry.netlify.app/)
---
I have...
I have...
> chore: add main cors entry

- server/__tests__/db/functions/authn/add_addr_to_account.test.ts
- server/__tests__/db/functions/authn/get_account_by_addr.test.ts
- server/__tests__/db/functions/authn/get_addrs_by_account_id.test.ts
- sql/authn/R__add_addr_to_account.sql
Closes: https://github.com/regen-network/regen-registry/issues/1078
---
I have...
I have...
> feat: make add_addr_to_account private

- server/__tests__/db/functions/authn/get_addrs_by_account_id.test.ts
- sql/authn/R__get_current_addrs.sql
Closes: https://github.com/regen-network/regen-registry/issues/1080
---
I have...
I have...
> feat: add profile_type in data from get_current_addrs

- sql/V2_16__party_grant.sql
Needed for regen-network/regen-registry#1423
As discussed, we'll be disabling row level security on `party` table manually on staging cc/ @wgwz 
---
I have...
I have...
> feat: add party migration

- server/package.json
- yarn.lock
This is a collection of dependency updates from dependabot. I reviewed all the updates and they look OK, no breaking changes, etc. This PR merges these changes into master. I tested locally and I also deployed these updates to the staging environment, looks good.
---
I have...
I have...
> chore: dependency updates

- .dockerignore
- .eslintrc.js
- .github/workflows/registryServer.yml
- Dockerfile
- docker-compose.yml
- package.json
- server/.env-test
- server/.env.example
- server/Server.ts
- server/__tests__/db/functions/authn/add_addr_to_account.test.ts
- server/__tests__/e2e/csrf.test.ts
- server/__tests__/e2e/web3auth.login.test.ts
- server/__tests__/e2e/web3auth.logout.test.ts
- server/__tests__/utils.ts
- server/middleware/csrf.ts
- server/package.json
- server/routes/csrf.ts
- server/routes/stripe.ts
- server/routes/web3auth.ts
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/1486
See the task above for a pretty thorough description of why I think we need to add this.
Also see the task above for some reasoning on the third-party library I chose to implement CSRF protection with.
Particularly useful to get started with this review, is this code, which shows exactly how to use an HTTP client to successfully pass CSRF protections:
https://github.com/regen-network/registry-server/blob/cdb16ca0bfd5a09e85e9adc303917084b1038783/server/__tests__/utils.ts#L12-L22
---
I have... …
> feat: csrf protection for login endpoints

- server/__tests__/db/helpers.ts
- server/middleware/keplrStrategy.ts
- sql/R__auth.sql
Closes: https://github.com/regen-network/regen-registry/issues/1523
Ref: https://github.com/regen-network/regen-registry/issues/1523#issuecomment-1404217443
---
I have...
I have...
> fix: mitigate potential sqli in login system

- server/.env.example
- server/Server.ts
Closes: regen-network/regen-registry#1545
Remove code related to Hambach.
---
I have...
I have...
> chore: remove hambach

- server/.env.example
- server/__tests__/e2e/csrf.test.ts
- server/__tests__/e2e/web3auth.login.test.ts
- server/__tests__/e2e/web3auth.logout.test.ts
- server/__tests__/utils.ts
- server/errors.ts
- server/middleware/keplrStrategy.ts
- server/middleware/passport.ts
- server/package.json
- server/routes/web3auth.ts
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/1086
- Adds e2e/integration tests for the login and logout endpoints for the login system
- Adds a middleware function called `ensureLoggedIn` that will be used to protect endpoints that require authentication
- Adds a "utils" module for the e2e/integration tests for deduping code across tests
---
I have...
I have...
> test: integration tests for keplr login endpoint

- server/Server.ts
- server/__tests__/db/functions/authn/add_addr_to_account.test.ts
- server/__tests__/db/functions/authn/update_party.test.ts
- server/__tests__/db/helpers.ts
- server/__tests__/e2e/web3auth.addresses.test.ts
- server/__tests__/e2e/web3auth.login.test.ts
- server/__tests__/e2e/web3auth.logout.test.ts
- server/__tests__/utils.ts
- server/errors.ts
- server/middleware/keplrStrategy.ts
- server/routes/web3auth.ts
- sql/authn/R__addr_can_be_added.sql
- sql/authn/R__get_current_account.sql
- sql/authn/R__get_current_account_id.sql
- sql/authn/R__get_current_addrs.sql
Closes: https://github.com/regen-network/regen-registry/issues/1079
- Adds an API endpoint for adding an address to a users account
- Adds tests for this new API endpoint
---
I have...
I have...
> feat: API for adding addresses

- server/Server.ts
- server/__tests__/db/functions/authn/add_addr_to_account.test.ts
- server/__tests__/db/functions/authn/update_party.test.ts
- server/__tests__/db/helpers.ts
- server/__tests__/e2e/web3auth.addresses.test.ts
- server/__tests__/e2e/web3auth.login.test.ts
- server/__tests__/e2e/web3auth.logout.test.ts
- server/__tests__/utils.ts
- server/errors.ts
- server/middleware/keplrStrategy.ts
- server/routes/web3auth.ts
- sql/authn/R__addr_can_be_added.sql
- sql/authn/R__get_current_account.sql
- sql/authn/R__get_current_account_id.sql
- sql/authn/R__get_current_addrs.sql
Closes: https://github.com/regen-network/regen-registry/issues/1535
---
I have...
I have...
> feat: enable double csrf protection on graphql endpoint

- docs/login-system.md
Closes: https://github.com/regen-network/regen-registry/issues/1550
View the formatted doc here:
https://github.com/regen-network/registry-server/blob/2d1e02da242147c4f80a2d6a31c100ab70b910f0/docs/login-system.md
---
I have...
I have...
> docs: add specification for login system

- sql/V2_23__add_party_bg_image.sql
Closes: https://github.com/regen-network/regen-registry/issues/1580
> Based on the current state of the keplr login PR and [the current desired state in front-end for related work][1],
> at this time we just need to add a field for the background image.
> We already have the RLS policy that ensures a user can only modify a party that belongs to them.
> We also [have tests to confirm this policy works][2] as intended.
[1]: https://github.com/regen-network/regen-registry/issues/1561
[2]: https://github.com/regen-network/registry-server/blob/kyle/1051-keplr-login-endpoints/server/__tests__/db/functions/authn/update_party.test.ts 
---
I have...
*All …
> feat: add bg_image to party table

- server/middleware/passport.ts
Fix for error below:
```
2023-03-14T20:13:45.708042+00:00 heroku[web.1]: Starting process with command `yarn serve`
2023-03-14T20:13:48.406346+00:00 app[web.1]: [heroku-exec] Starting
2023-03-14T20:13:49.974913+00:00 app[web.1]: yarn run v1.22.19
2023-03-14T20:13:50.035914+00:00 app[web.1]: $ lerna run --scope=registry-server start --stream
2023-03-14T20:13:50.630824+00:00 app[web.1]: lerna notice cli v4.0.0
2023-03-14T20:13:50.708882+00:00 app[web.1]: lerna notice filter including "registry-server"
2023-03-14T20:13:50.709560+00:00 app[web.1]: lerna info filter [ 'registry-server' ]
2023-03-14T20:13:50.711784+00:00 app[web.1]: lerna info Executing command in 1 package: "yarn run start"
2023-03-14T20:13:51.272286+00:00 app[web.1]: registry-server: $ ts-node Server.ts …
```
> fix: use any to bypass heroku typescript compilation issue

- server/middleware/passport.ts
- server/package.json
- server/routes/web3auth.ts
I believe this could fix the TS issues described in https://github.com/regen-network/registry-server/pull/298 and https://github.com/regen-network/registry-server/pull/299, tried to deploy on heroku from this branch and didn't run into the issue
---
I have...
I have...
> fix: ts req error

- server/Server.ts
- server/middleware/csrf.ts
- server/utils.ts
Closes: https://github.com/regen-network/regen-registry/issues/1596
---
I have...
I have...
> feat: make csrf cookie security properties configurable

- server/__tests__/e2e/authn/party.update.policy.test.ts
Closes: #306 
---
I have...
I have...
> test: party update policy e2e

- sql/V2_24__add_party_social_links.sql
Closes: https://github.com/regen-network/regen-registry/issues/1616
Add migration for user social links in the party table.
Related registry PR: https://github.com/regen-network/regen-web/pull/1839
---
I have...
I have...
> feat: add migration for party social links

- .github/workflows/registryServer.yml
- docker-compose.yml
- server/.env-test
- server/.gitignore
- server/__tests__/db/functions/authn/get_parties_by_account_id.test.ts
- server/__tests__/e2e/files.test.ts
- server/__tests__/utils.ts
- server/jest.config.js
- server/jestSetupFile.ts
- server/package.json
- server/routes/files.ts
- server/routes/web3auth.ts
- sql/authn/R__get_parties_by_account_id.sql
- tsconfig.json
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/1636
---
I have...
I have...
> feat: check auth for profiles uploads

- server/__tests__/db/wallet.delete.policy.test.ts
- server/__tests__/db/wallet.insert.policy.test.ts
- server/__tests__/db/wallet.select.policy.test.ts
- server/__tests__/db/wallet.update.policy.test.ts
- sql/V2_25__wallet_policies.sql
Closes: https://github.com/regen-network/regen-registry/issues/1629
---
I have...
I have...
> feat: add wallet policy

- server/__tests__/db/wallet.delete.policy.test.ts
- server/__tests__/db/wallet.insert.policy.test.ts
- server/__tests__/db/wallet.select.policy.test.ts
- server/__tests__/db/wallet.update.policy.test.ts
- sql/V2_25__wallet_policies.sql
Closes: #XXXX
---
I have...
I have...
> feat: add wallet policy (#316)

- .gitignore
- package.json
- server/Server.ts
- server/package.json
- server/routes/graphiql.ts
- server/views/graphiql.html
Closes: https://github.com/regen-network/regen-registry/issues/1591
Deployed to staging for testing:
https://api-staging.registry.regen.network/graphiql
---
I have...
I have...
> feat: add graphiql instance that uses csrf-csrf

- server/__tests__/db/project.delete.policy.test.ts
- server/__tests__/db/project.insert.policy.test.ts
- server/__tests__/db/project.update.policy.test.ts
- server/__tests__/db/wallet.delete.policy.test.ts
- server/__tests__/db/wallet.insert.policy.test.ts
- server/__tests__/db/wallet.select.policy.test.ts
- server/__tests__/db/wallet.update.policy.test.ts
- server/__tests__/e2e/authn/party.update.policy.test.ts
- server/__tests__/e2e/files.profiles.test.ts
- server/__tests__/e2e/files.projects.test.ts
- server/__tests__/e2e/web3auth.addresses.test.ts
- server/__tests__/e2e/web3auth.login.test.ts
- server/__tests__/e2e/web3auth.logout.test.ts
- server/__tests__/utils.ts
- server/routes/files.ts
Closes: https://github.com/regen-network/regen-registry/issues/1660
---
I have...
I have...
> feat: project media can only be updated by admins

- server/package.json
- yarn.lock
Closes: #XXXX
---
I have...
I have...
> chore: add yarn start-dev which uses nodemon

- migrations/committed/000002.sql
Closes: https://github.com/regen-network/regen-registry/issues/1697
---
I have...
I have...
> feat: add verifier to project and registry to credit class

- server/Server.ts
> fix: remove type from workaround middleware for cookie-session/passport

- server/__tests__/e2e/web3auth.addresses.test.ts
- server/routes/web3auth.ts
Closes: https://github.com/regen-network/regen-registry/issues/1708
---
I have...
I have...
> fix: create role for previously unused address when adding an address

- server/routes/files.ts
Closes: https://github.com/regen-network/regen-registry/issues/1683
This PR switches the `/files` endpoints to make use of the newer AWS SDK for S3.
That's all that was needed to fix the issue with large file uploads to these endpoints.
Using a fairly large file (100MiB), I found that in the current staging (or production) environment we get this failure:
```
➜  ~ http -f POST https://api-staging.registry.regen.network/files filePath=kyle-test image@~/data-100MiB.bin 
HTTP/1.1 500 Internal Server Error
{
"Error": {
"code": "MalformedXML",
"extendedRequestId": "ft+qnaoFYQaYJ8/WTlWJtwOkLR0H7Nzcphy1V9Sqhuvqg1wi2dj18+r+i1+DizUQQIYqyY/mlzM=",
"message": "The XML you provided was not well-formed or did not validate against our published schema",
"region": null,
"requestId": "DD3X963T01FHAV0Y", …
```
> fix: large uploads to s3 through files endpoint

- migrations/committed/000005.sql
- migrations/schema_snapshot.sql
- server/__tests__/db/functions/get_parties_by_name_or_addr.test.ts
Needed for regen-network/regen-registry#1504
---
I have...
I have...
> feat: add get_parties_by_name_or_addr function

- server/Server.ts
- server/package.json
- yarn.lock
Closes: https://github.com/regen-network/regen-registry/issues/1463
---
I have...
I have...
> chore: only send errors to sentry and remove sentry tracing

- common/pool.ts
- server/.env.example
- server/Server.ts
- server/routes/graphiql.ts
- server/views/analyticsGraphiql.html
- server/views/indexerGraphiql.html
Closes: https://github.com/regen-network/regen-registry/issues/1742
---
I have...
I have...
> feat: new graphql and graphiql endpoints for analytics db

- common/pool.ts
- server/Server.ts
Closes: https://github.com/regen-network/regen-registry/issues/1750
---
I have...
I have...
> fix: pool settings to allow connect to prod from local

- server/Server.ts
Closes: https://github.com/regen-network/regen-registry/issues/1749
---
I have...
I have...
> chore: add env var to toggle CORS

- common/pool.ts
- server/Server.ts
Closes: #XXXX
---
I have...
I have...
> Dev to master

- server/Server.ts
Part of: https://github.com/regen-network/groups-ui/pull/112
---
I have...
I have...
> fix: add groups ui deploy previews and main deploy to CORS allow list

- README.md
- common/package.json
- docs/login-system.md
- iri-gen/package.json
- migrations/README.md
- server/Server.ts
- server/middleware/jwt.ts
Closes: https://github.com/regen-network/regen-web/issues/1961
---
I have...
I have...
> chore: rename registry server to regen server

- server/Server.ts
Part of: https://github.com/regen-network/regen-server/pull/360
---
I have...
- [x ] targeted `dev` branch
- [x ] provided a link to the relevant issue or specification
- [x ] reviewed "Files changed" and left comments if necessary
- [x ] confirmed all CI checks have passed
I have...
> fix: add groups-ui branch deploys to CORS allowlist

- server/Server.ts
Closes: #366
This pull request updates the netlify domain for CORS configuration for deploy previews to `regen-marketplace`.
---
I have...
I have...
> chore: update deploy preview cors configuration

- docs/manual-profiles.md
Closes: #364 
Markdown Preview: https://github.com/regen-network/regen-server/blob/kyle/364-manual-profiles/docs/manual-profiles.md
---
I have...
I have...
> docs: manual profiles

- migrations/committed/000008.sql
- migrations/schema_snapshot.sql
- server/__tests__/db/project.update.policy.test.ts
Closes: #369 
---
I have...
I have...
> feat: add approved column to projects table

- docs/manual-profiles.md
> docs(fix): fix update sql to use party.id

- migrations/committed/000011.sql
- migrations/schema_snapshot.sql
Part of regen-network/regen-web#2113
---
I have...
I have...
> chore: rename project handle to slug

- migrations/committed/000012.sql
- migrations/schema_snapshot.sql
Closes: 
regen-network/regen-web#2116
- add a published column to `project` table
---
I have...
I have...
> feat: add published column to project table

- docs/login-system.md
- migrations/committed/000043.sql
- migrations/schema_snapshot.sql
- server/Server.ts
- server/__tests__/e2e/wallet-auth.login.test.ts
- server/__tests__/e2e/wallet-auth.logout.test.ts
- server/__tests__/unit/auth.passcode.test.ts
- server/__tests__/unit/wallet-auth.connect-wallet.test.ts
- server/__tests__/unit/web3auth.connect-wallet.test.ts
- server/__tests__/utils.ts
- server/errors.ts
- server/middleware/googleStrategy.ts
- server/middleware/keplrStrategy.ts
- server/middleware/passcodeStrategy.ts
- server/routes/wallet-auth.ts
- server/routes/web3auth.ts
Closes: #409
---
I have...
I have...
> feat: connect wallet to an existing account

- migrations/committed/000044.sql
- migrations/committed/000045.sql
- migrations/schema_snapshot.sql
- server/__tests__/db/functions/authn/create_new_web2_account.test.ts
- server/__tests__/e2e/auth.accounts.test.ts
- server/__tests__/unit/auth.connect-google.test.ts
- server/__tests__/unit/auth.google.test.ts
- server/__tests__/unit/auth.passcode.test.ts
- server/__tests__/utils.ts
- server/middleware/connectGoogleStrategy.ts
- server/middleware/googleStrategy.ts
- server/middleware/passport.ts
- server/routes/auth.ts
Closes: #410
---
I have...
I have...
> feat: connect/disconnect existing account to/from google

- server/__tests__/unit/auth.connect-google.test.ts
- server/__tests__/unit/auth.passcode.test.ts
- server/middleware/connectGoogleStrategy.ts
Closes: #433
---
I have...
I have...
> fix: set main email to google email if not set to preserve uniqueness across main email and google email

- migrations/committed/000048.sql
- migrations/committed/000049.sql
- migrations/schema_snapshot.sql
ref: https://github.com/regen-network/rnd-dev-team/issues/1857
---
I have...
I have...
> feat: add project_partner table

- .github/workflows/registryServer.yml
Closes: #XXXX
---
I have...
I have...
> chore: run CI on PRs

- migrations/committed/000050.sql
- migrations/schema_snapshot.sql
https://regennetwork.atlassian.net/browse/APP-80?atlOrigin=eyJpIjoiNmY0YzVhOTkyYjc1NGI5ZjkxNThjNGQxM2VhNTJiYTIiLCJwIjoiaiJ9
---
I have...
I have...
> feat: APP-80 add hide_ecocredits and hide_retirements to account table

- .github/workflows/registryServer.yml
- migrations/committed/000050.sql
- migrations/schema_snapshot.sql
Closes: #XXXX
---
I have...
I have...
> chore(release): dev to master

- .github/workflows/registryServer.yml
Closes: #XXXX
---
I have...
I have...
> chore: remove duplicate yarn step

- migrations/committed/000051.sql
- migrations/schema_snapshot.sql
Closes: #449
---
I have...
I have...
> fix: APP-85 replace iri with uuid for upload pk

- server/__tests__/e2e/files.projects.test.ts
- server/__tests__/e2e/post.mock.ts
- server/__tests__/e2e/posts.delete.test.ts
- server/__tests__/e2e/posts.get.test.ts
- server/__tests__/e2e/posts.post.test.ts
- server/__tests__/e2e/posts.project.get.test.ts
- server/__tests__/e2e/posts.put.test.ts
- server/__tests__/unit/posts.get-post-data.test.ts
- server/__tests__/utils.ts
- server/routes/files.ts
- server/routes/posts.ts
Needed for https://regennetwork.atlassian.net/browse/APP-24?atlOrigin=eyJpIjoiZmE3YmFmZjA4MGFkNDVkMzg3ZWQzNzEyNGZjNzY4OWYiLCJwIjoiaiJ9
- Using latest post schema from @paul121: https://gist.github.com/paul121/1d83c0d4dcdf06c3bcff44a4c42cffd7 
- Returning file IRI as part of the POST /files response
- Fixing a bug in post files deletion, reported by @wgardiner
---
I have...
I have...
> fix: update to latest post schema and delete post files

- migrations/committed/000052.sql
- migrations/schema_snapshot.sql
- server/__tests__/unit/wallet-auth.connect-wallet.test.ts
- server/__tests__/unit/wallet-auth.merge-accounts.test.ts
- server/__tests__/utils.ts
- server/routes/files.ts
- server/routes/wallet-auth.ts
Part of https://regennetwork.atlassian.net/browse/APP-115?atlOrigin=eyJpIjoiZGE5OTIwZWNjNTYwNGM3ZGI4NmY2NjdmZTY0MjA3MTkiLCJwIjoiaiJ9
---
I have...
I have...
> feat: APP-115 account merging

- server/__tests__/e2e/posts.project.get.test.ts
- server/routes/posts.ts
needed for: https://regennetwork.atlassian.net/browse/APP-23?atlOrigin=eyJpIjoiNGZjYTE2N2Y2YTgwNDc4Y2FjMTY5OGJkNTZkMTkxYjEiLCJwIjoiaiJ9
---
I have...
I have...
> feat: return total posts per year in GET posts by project

- migrations/committed/000053.sql
- migrations/schema_snapshot.sql
- server/__tests__/e2e/files.projects.test.ts
- server/routes/files.ts
- server/routes/posts.ts
- server/worker/tasks/delete_s3_file.ts
https://regennetwork.atlassian.net/browse/APP-181?atlOrigin=eyJpIjoiMjE1NGE5NTJiMTVlNDMyMzhjNmFlMTFiNzBjYTA4ZjkiLCJwIjoiaiJ9
---
I have...
I have...
> feat: APP-181 add a postgraphile worker task to delete files from s3
